#!/bin/sh

case "$1" in
    start)
	if [ -f /home/uxas/run_uxas.sh ]; then
            daemon --user=uxas --chdir=/home/uxas/run -- /bin/sh /home/uxas/run_uxas.sh;
        fi
	;;
    stop)
        # note: the run_uxas.sh script might start an executable other
        # than uxas; this is a best guess
        killall -q uxas
        ;;
    *)
	;;
esac

exit $?
